# This workflow will build and deploy a project to genezio
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create a free genezio account at https://genez.io
#
# 2. Store a genezio access token in GitHub Actions secrets named `GENEZIO_TOKEN`.
#
# See the documentation for more details and best practices.
# https://docs.genez.io/genezio-github-action

name: Deploy to genezio
on:
  push:

    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup genezio
        uses: Genez-io/genezio-github-action@main
        with:
          genezio-version: latest
          token: ${{ secrets.GENEZIO_TOKEN }}
      - name: Deploy with genezio
        working-directory: ./server
        run: genezio deploy
        env:
          CI: false
